alias: "6m Aurora Propagation Alert"
description: ""
triggers:
  - trigger: state
    entity_id: sensor.amateur_radio_propagation_solar_vhf_aurora
    to: "Yes"
conditions: []
actions:
  - data:
      message: "6m Aurora propagation detected!"
      title: "📡 6m Aurora Open"
    action: notify.mobile_app_iphone
mode: single

