alias: "6m E-Skip Band Open Alert"
description: ""
triggers:
  - trigger: state
    entity_id: sensor.amateur_radio_propagation_solar_vhf_eskip_na
    to: "Yes"
conditions: []
actions:
  - data:
      message: "6m sporadic E is open!"
      title: "📡 6m Band Open"
    action: notify.mobile_app_iphone
mode: single

